# Generated by Django 4.2.7 on 2023-11-03 21:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='customer_images/')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
